apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-flow-break-test-13-v1-0-0
  labels:
    app: app-flow-break-test-13-v1-0-0
    applicationId: app_4b0a16a8-ba31-4124-be9f-ba0e25d4d8f9
    version: v1.0.0
    organizationId: org_b90db410-70ec-4efc-955f-90fee843d8f8
    projectId: project_40190942-a07e-4c64-ae19-c48fc07c6763
spec:
  selector:
    matchLabels:
      app: app-flow-break-test-13-v1-0-0
  template:
    metadata:
      labels:
        app: app-flow-break-test-13-v1-0-0
