apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: app-flow-break-test-9-v1-0-0
    applicationId: app_b26b0ea6-f823-466f-a659-8efc31325baa
    version: v1.0.0
    organizationId: org_b90db410-70ec-4efc-955f-90fee843d8f8
    projectId: project_40190942-a07e-4c64-ae19-c48fc07c6763
  name: app-flow-break-test-9-v1-0-0
spec:
  selector:
    app: app-flow-break-test-9-v1-0-0
