apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: app-flow-break-test-12-v1-0-0
    applicationId: app_d278f590-926a-411e-80c5-f11180838668
    version: v1.0.0
    organizationId: org_b90db410-70ec-4efc-955f-90fee843d8f8
    projectId: project_40190942-a07e-4c64-ae19-c48fc07c6763
  name: app-flow-break-test-12-v1-0-0
spec:
  selector:
    app: app-flow-break-test-12-v1-0-0
