apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: app-flow-break-test-3-v1-0-0
  labels:
    app: app-flow-break-test-3-v1-0-0
    applicationId: app_ec5b4b6f-4824-48c7-9e5e-9045ce84b0a8
    version: v1.0.0
    organizationId: org_b90db410-70ec-4efc-955f-90fee843d8f8
    projectId: project_40190942-a07e-4c64-ae19-c48fc07c6763
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-flow-break-test-3-v1-0-0
