apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-flow-break-test-18-v1-0-0
  labels:
    app: app-flow-break-test-18-v1-0-0
    applicationId: app_bef2cb8e-d323-4a83-add4-47becd58f960
    version: v1.0.0
    organizationId: org_b90db410-70ec-4efc-955f-90fee843d8f8
    projectId: project_40190942-a07e-4c64-ae19-c48fc07c6763
spec:
  selector:
    matchLabels:
      app: app-flow-break-test-18-v1-0-0
  template:
    metadata:
      labels:
        app: app-flow-break-test-18-v1-0-0
