apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: deploy-stats-check-app-v1-0-0
  labels:
    app: deploy-stats-check-app-v1-0-0
    applicationId: app_41634251-1941-4c73-914b-858650d6193d
    version: v1.0.0
    organizationId: org_b90db410-70ec-4efc-955f-90fee843d8f8
    projectId: project_40190942-a07e-4c64-ae19-c48fc07c6763
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy-stats-check-app-v1-0-0
