apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: app-flow-break-test-14-v1-0-0
    applicationId: app_42005f66-d553-4c58-8ff7-5da1ecdb5bfc
    version: v1.0.0
    organizationId: org_b90db410-70ec-4efc-955f-90fee843d8f8
    projectId: project_40190942-a07e-4c64-ae19-c48fc07c6763
  name: app-flow-break-test-14-v1-0-0
spec:
  selector:
    app: app-flow-break-test-14-v1-0-0
