apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: app-flow-break-test-15-main
      imagePullPolicy: Always
      imageRegistry: sdfsdsdfssdfsdf/zxczxzxdzdxfc
      imagePullSecretName: imagepull-docker
      credentialId: credential_a2a7a258-c791-4404-97c7-6bc86a6f01f4
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: app-flow-break-test-15
    version: v1.0.0
    applicationId: app_d1ea16b8-c01e-493b-bf99-922ce012e263
    projectId: project_40190942-a07e-4c64-ae19-c48fc07c6763
    organizationId: org_b90db410-70ec-4efc-955f-90fee843d8f8
    environmentId: env_4479528d-5cbf-428a-82f0-9a2263baa9b8
    environmentName: test-environment-2
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: app-flow-break-test-15
  cronTab: ''
  serviceType: ClusterIP
  version: v1.0.0
  namespace: test-foo
